### ISSUE TITLE
Tidy up API documentation

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller-adaptor#7]
There is a group of API endpoints related to the state report management which is currently titled "CyberKit4SME". As these endpoints are, by design, generic, they should not have the project name associated with them. Please find another name, such as "State Report Management" if that's appropriate.

The individual method descriptions need reviewing and revising as some of them are out of date. They should not be mentioning specific external integrations such as "Keenai" as the methods are generic.

**Comment by panositi** [comment]
FastAPI allows to group endpoints in groups. It is a very simple change to rename that group. There is also the [SIEA](https://cyberkit4sme1.it-innovation.soton.ac.uk/system-modeller/adaptor/docs#/SIEA) and [AdaptationCoordinator](https://cyberkit4sme1.it-innovation.soton.ac.uk/system-modeller/adaptor/docs#/AdaptationCoordinator) which are very specific FogProtect groups of endpoints that need to be addressed too.

There is also in `.env_adaptor` parameter that controls which the groups of the API endpoints that will be visible on a particular deployment e.g.
```
# Adaptor mode: values [All, ProTego, FogProtect]
SSM_ADAPTOR_MODE=all
```
All that needs to be updated too.
